# Generated by Django 5.1.2 on 2024-11-14 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_options_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=2000)),
                ('posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
